### PR TITLE
Implement client.readByKey + add client.reset() docs

### PR DESCRIPTION
**Pull request by adjourn**
Thanks for quick contribution guide, it helped a lot. I decided to give it a shot because it's relatively easy thing to implement and good PR to try out these new technologies (Lerna and TypeScript).

Im still not sure about types though but edits are allowed, I encourage you to make changes if needed.

Closes: #75

### CODE REVIEW

**Comment by malbernaz** [comment]
Hey, @adjourn implementation wise this looks great!

And it's awesome that the contributing guide was helpful for you!


I still have some doubts about the naming though. The term `key` makes reference to an internal (`objectsMap`). I was thinking more of something like `findByID`. That's because

**Comment by malbernaz** [comment]
Sorry about the mess, closing reopening mess... I pressed a few buttons unintentionally.

Implementation wise this looks great!

Two things:

- I still have some doubts about the naming. The term `key` refers to an internal implementation. I think `id` would work better as it would pair with `idFields`.

- For some reason the CI is not running. I'll investigate what's happening and try to fix it today.

**Comment by malbernaz** [comment]
ci problem solved

**Comment by adjourn** [comment]
:+1: 

Agreed, `id` would be better. My initial rationale was that it could be composite (e.g `type:id`) and `id` probably already has a meaning for user - `id` field.  Are you going to wrap this up yourself or want me to?

I guess this is the best time to ask if maybe `getByID` would be better than `readById()`?

**Comment by mogelbrod** [comment]
I agree that `id` could easily be confused with `idFields`. `key` is often used for composite values and thus the choice I'd go with for the API implemented here.

**Comment by malbernaz** [comment]
I'm tending towards merging this.

But I thinking here: client could benefit a lot if it had `get`, `set`, `delete` methods like a javascript `Map`. Something like:

```js
client.get([someID])
// or
client.objects.get([someID])
```

what do you guys think?

**Comment by malbernaz** [comment]
It will be easier to maintain consistence if we are to implement `remove` and `set` in the future.

**Comment by mogelbrod** [comment]
I'm all for consistency with `Map` in regards to method naming (get/set), maybe even go as far as extending it (although it might lock the API down a bit?). I do however think making `get()` and `delete` dual-purpose through an optional argument is dangerous, since accidental calls with `undefined` would return/clear the whole cache instead of just a part of it. `Map` has a different method for `clear`ing as an example.

**Comment by adjourn** [comment]
@malbernaz Im all in, these keywords are different enough from `read` and `write`, it should be obvious rather quickly that these are for imperative- and `read`, `write` are for GraphQL actions.

I also agree on dual-purpose, deleting single item or whole cache should have different keywords but I wouldn't mind dual-purpose for example `client.delete(key) and client.delete(query, variables)`.

**Comment by malbernaz** [comment]
> I do however think making `get()` and `delete` dual-purpose through an optional argument is dangerous

For sure! The responsibilities are completely different.

Now, what about wrapping these map like methods in a client property (eg. `client.objects`)?

@adjourn, would you like to extend this pull request further and implement this functionality?

**Comment by adjourn** [comment]
Do you mean change current API to `get` or other functionality too?

I haven't wrapped my head around everything in this library yet but I have some idea how to delete by query and variables. By key is a different story, Im not sure what's the best way to find correct object from `pathsMap`. Looping over whole map seems like a terrible idea..

Another thing to addess: should we invoke listeners on `set` and `delete`?

**Comment by mogelbrod** [comment]
Loving the rate of replies right now 💯 
If going the sub-object route I'd use `cache` since that's what it is (objects is a little too ambiguous).
If `read` and `write` stays along with `get` and `set` I'd say that it needs it's own `delete`/`remove` method to be consistent (`discard` or similar to align with read/write). This would however make the API contain 2 different interaction "segments" that'll probably be confusing for new users, as well as problematic when extending the API in the future. I'm not really sure about which approach would be the best going forward.

**Comment by malbernaz** [comment]
> Loving the rate of replies right now 💯

It's really cool to have people involved in this project!

@adjourn, you are right. This is not a trivial change, and there's a of reasoning to be made.

Maybe just calling the listener without an argument would be fine for `set` and `delete`, but there's some testing to be done.

I'll tell you what. Are you depending on `readByKey` for some work you are doing right now? If so I can merge this and include the Map API in 2.0.

@mogelbrod maybe isolating the map API in a client property would probably make things clearer. And of course, documentation is crucial to make users aware of the fact.

**Comment by adjourn** [comment]
Not using it right now and if I did, I could easily make a local build (which I already have for experimenting). 

I think we should start with generating query id feature and work up from there, Im already looking for options. 

In my opinion whole query string as a key thing could be replaced with hash ids which would simplify some things, have shorter keys and it just feels more right. Then we'd have a solid base to add features, optimize (e.g memoize ids) and think of better ways to do things in the future. Of course I could be missing something at this point. What's your opinion?

Could you explain this part?

```js 
// util.ts
export let getPathId = (path: string, args: string[], variables?: Variables) => {
  variables = variables || {};
  let finalPath = path;
  let i = args.length;

  // this right here
  // variables[args[i]] is usually undefined because
  // args (idFields) are rarely the same as variables
  while (i--) finalPath += ":" + variables[args[i]];

  return finalPath;
};
```

Should open a new issue to discuss this, otherwise it's all over the place or even open umbrella issue to discuss possible changes and maintain a TODO list.

**Comment by malbernaz** [comment]
> Maybe we should start with generating hash id feature and work up from there, I've already made a prototype, probably going to PR today.

Please do!

> should we keep using selections as path ids or generate hashes for these too?

There's nothing preventing us from that. We could even use an integer. I've went this path because it spares work with query deduplication. The piece of code below runs more then once.

```js
grafooObj.paths[selectionSet] = {/*...*/}
```

Can you open an issue for that?

> Then we could maybe add cross-references between object and path maps without too big values - `set, delete` by key would be a lot better without looping over whole map.

The algorithm to build query data traverses a path and update the items based on `objectsMap`, but `objectsMap` keys are irrelevant to the process.

I'm closing this.

**Pull request closed without merging**
